
const questions = [
    {
        roundid: '0',
        title: 'Forms',
        status: 'playing',
        type: 'form',
        questions: [
            {
                id: 101,
                title: 'Name Entry',
                roundid: '0',
                type: 'form',
                leadSentence: '本大会で使用する名前を登録します。この名前は、成績発表において公開されることがあります。',
                instruction: 'Your Name',
                status: 'playing',
            },
            {
                id: 102,
                title: 'Team Entry',
                roundid: '0',
                type: 'form',
                leadSentence: '本大会で使用するチーム名を登録します。この名前は、成績発表において公開されることがあります。',
                instruction: 'Team Name',
                status: 'playing',
            },
        ],
    },
    {
        roundid: '1',
        title: '1st Round',
        status: 'playing',
        type: 'question',
        questions: [
            {
                id: 1,
                title: '[A]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'accepted',
                teammateViewing: false,
            },
            {
                id: 2,
                title: '[B]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
                teammateViewing: false,
            },
            {
                id: 3,
                title: '[C]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'banned',
                teammateViewing: false,
            },
            {
                id: 4,
                title: '[D]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
                teammateViewing: false,
            },
            {
                id: 5,
                title: '[E]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
                teammateViewing: false,
            },
            {
                id: 6,
                title: '[F]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
                teammateViewing: false,
            },
            {
                id: 7,
                title: '[G]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
                teammateViewing: false,
            },
            {
                id: 8,
                title: '[H]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
                teammateViewing: false,
            },
            {
                id: 9,
                title: '[I]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
                teammateViewing: false,
            },
            {
                id: 10,
                title: '[J]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
                teammateViewing: false,
            },
            {
                id: 11,
                title: '[K]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
                teammateViewing: false,
            },
            {
                id: 12,
                title: '[L]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
                teammateViewing: false,
            },
            {
                id: 13,
                title: '[M]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
                teammateViewing: false,
            },
            {
                id: 14,
                title: '[N]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
                teammateViewing: false,
            },
            {
                id: 15,
                title: '[O]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
                teammateViewing: false,
            },
            {
                id: 16,
                title: '[P]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
                teammateViewing: false,
            },
            {
                id: 17,
                title: '[Q]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
                teammateViewing: false,
            },
            {
                id: 18,
                title: '[R]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
                teammateViewing: false,
            },
            {
                id: 19,
                title: '[S]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
                teammateViewing: false,
            },
            {
                id: 20,
                title: '[T]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
                teammateViewing: false,
            },
            {
                id: 21,
                title: '[U]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
                teammateViewing: false,
            },
            {
                id: 22,
                title: '[V]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
                teammateViewing: false,
            },
            {
                id: 23,
                title: '[W]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
                teammateViewing: false,
            },
            {
                id: 24,
                title: '[X]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
                teammateViewing: false,
            },
            {
                id: 25,
                title: '[Y]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
                teammateViewing: false,
            },
        ],
    },
    {
        roundid: '2',
        title: '2nd Round',
        status: 'ready',
        type: 'question',
        questions: [
            {
                id: 31,
                title: '[alpha]',
                roundid: '2',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
            },
            {
                id: 32,
                title: '[beta]',
                roundid: '2',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'ready',
            },
            {
                id: 33,
                title: '[gamma]',
                roundid: '2',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'ready',
            },
        ],
    },
    {
        roundid: '3',
        title: 'Extra Round',
        status: 'playing',
        type: 'question',
        questions: [
            {
                id: 40,
                title: '[Revival]',
                roundid: '3',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'hidden',
            },
        ],
    },
]

export default questions;