
const questions = [
    {
        roundid: '0',
        title: 'Forms',
        status: 'playing',
        type: 'form',
        questions: [
            {
                id: 'Entry',
                title: 'Name Entry',
                roundid: '0',
                type: 'form',
                leadSentence: '本大会で使用する名前を登録します。この名前は、成績発表において公開されることがあります。',
                instruction: 'Your Name',
                status: 'playing',
            },
            {
                id: 'TEntry',
                title: 'Team Entry',
                roundid: '0',
                type: 'form',
                leadSentence: '本大会で使用するチーム名を登録します。この名前は、成績発表において公開されることがあります。',
                instruction: 'Team Name',
                status: 'playing',
            },
        ],
    },
    {
        roundid: '1',
        title: '1st Round',
        status: 'playing',
        type: 'question',
        questions: [
            {
                id: 'A',
                title: '[A]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'accepted',
            },
            {
                id: 'B',
                title: '[B]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'teammateViewing',
            },
            {
                id: 'C',
                title: '[C]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'banned',
            },
            {
                id: 'D',
                title: '[D]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
            },
            {
                id: 'E',
                title: '[E]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
            },
            {
                id: 'F',
                title: '[F]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
            },
            {
                id: 'G',
                title: '[G]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
            },
            {
                id: 'H',
                title: '[H]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
            },
            {
                id: 'I',
                title: '[I]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
            },
            {
                id: 'J',
                title: '[J]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
            },
            {
                id: 'K',
                title: '[K]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
            },
            {
                id: 'L',
                title: '[L]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
            },
            {
                id: 'M',
                title: '[M]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
            },
            {
                id: 'N',
                title: '[N]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
            },
            {
                id: 'O',
                title: '[O]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
            },
            {
                id: 'P',
                title: '[P]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
            },
            {
                id: 'Q',
                title: '[Q]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
            },
            {
                id: 'R',
                title: '[R]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
            },
            {
                id: 'S',
                title: '[S]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
            },
            {
                id: 'T',
                title: '[T]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
            },
            {
                id: 'U',
                title: '[U]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
            },
            {
                id: 'V',
                title: '[V]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
            },
            {
                id: 'W',
                title: '[W]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
            },
            {
                id: 'X',
                title: '[X]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
            },
            {
                id: 'Y',
                title: '[Y]',
                roundid: '1',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
            },
        ],
    },
    {
        roundid: '2',
        title: '2nd Round',
        status: 'ready',
        type: 'question',
        questions: [
            {
                id: 'alpha',
                title: '[alpha]',
                roundid: '2',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'playing',
            },
            {
                id: 'beta',
                title: '[beta]',
                roundid: '2',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'ready',
            },
            {
                id: 'gamma',
                title: '[gamma]',
                roundid: '2',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'ready',
            },
        ],
    },
    {
        roundid: '3',
        title: 'Extra Round',
        status: 'playing',
        type: 'question',
        questions: [
            {
                id: 'Z',
                title: '[Z]',
                roundid: '3',
                type: 'question',
                img: 'https://juicy-apple.fun/av/AVRC2019/images/Final-2.png',
                status: 'hidden',
            },
        ],
    },
]

export default questions;