const Styles = (theme) => ({
    Header: {
        width: '100%',
        height: '10%',
        position: 'fixed',
        textAlign: 'center',
        bottom: '0%',
        left: '0',
        display: 'flex',
        flexWrap: 'nowrap',
        alignItems: 'center',
    },   
    HeaderBackWrapper: {
        width: '40%',
        marginLeft: '5%',
        height: '100%',
        display: 'flex',
        flexWrap: 'nowrap',
        alignItems: 'center',
        justifyContent: 'center',
        opacity: '0.8',
    },   
    HeaderBackButton: {
        width: '100%',
        minHeight: '40px',
        position: 'relative',
        backgroundColor: '#fff',
        borderRadius: '10px',
        boxShadow: '0px 0px 5px 5px rgba(40, 40, 40, 0.2)',
        textDecoration: 'none',
        color: '#333',
        display: 'flex',
        alignItems: 'center',
    },
    HeaderBackArrow: {
        width: '20%',
        height: 'auto',
        color: '#333',
        display: 'block'
    },
    HeaderTitleWrapper: {
        width: '60%',
        height: '100%',
        display: 'flex',
        flexWrap: 'nowrap',
        alignItems: 'center',
        justifyContent: 'center',
    },
    AnswerSheet: {
        width: '100%',
        maxHeight: '90%',
        overflow: 'scroll',
        margin: '0',
        padding: '20px',
        background: 'rgba(255, 255, 255, 0.5)',
        boxShadow: '3px 3px 1px 1px rgba(40, 40, 40, 0.2), inset 0 0 10px 0 #fff',
        display: 'flex',
        flexWrap: 'wrap',
        justifyContent: 'center',
    },
    SheetHeader: {
        width: '100%',
        textAlign: 'center',
    },
    QuestionWrapper: {
        width: '90%',
        minHeight: '60px',
        position: 'relative',
        padding: '10px',
        display: 'flex',
        flexWrap: 'wrap',
        '&::before': {
            content: '""',
            width: '20px',
            height: '30px',
            position: 'absolute',
            display: 'inline-block',
            top: '0',
            left: '0',
            borderLeft: '#999 1px solid',
            borderTop: '#999 1px solid',
            pointerEvents: 'none',
        },
        '&::after': {
            content: '""',
            width: '20px',
            height: '30px',
            position: 'absolute',
            display: 'inline-block',
            bottom: '0',
            right: '0',
            borderRight: '#999 1px solid',
            borderBottom: '#999 1px solid',
            pointerEvents: 'none',
        },
    },
    img: {
        width: '100%',
        height: 'auto',
        alignSelf: 'center'
    },
    Form: {
        margin: '40px 0',
        width: '100%',
        display: 'flex',
    },
    answerField: {
        flexGrow: '5',
    },
    submitButton: {
        flexGrow: '1',
        margin: '0 3%',
    },
    Footer: {
        width: '100%',
        minHeight: '10px',
        textAlign: 'center',
    },
    footerImg: {
        maxWidth: '40%',
        height: 'auto',
    },
    QuestionLinkWrapper: {
        width: '20%',
        position: 'relative',
        '&::before': {
            content: '""',
            display: 'block',
            width: '100%',
            paddingTop: '100%',
        },
        '&.large': {
            width: '100%',
            '&::before': {
                content: '""',
                display: 'block',
                width: '100%',
                paddingTop: '20%',
            },
        }
    },
    QuestionLinkBlock: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        position: 'absolute',
        top: '0',
        left: '0',
        right: '0',
        bottom: '0',
        boxSizing: 'border-box',
        border: '#5eb6ff 1px solid',
        boxShadow: 'inset 0 0 5px 0 #5eb6ff',
        backgroundColor: 'rgba(94, 182, 255, 0.3)',
        borderRadius: '3px',
        margin: '2px',
        '&.banned': {
            opacity: '0.3',
            border: '#555 1px solid',
            boxShadow: 'inset 0 0 5px 0 #555',
            backgroundColor: 'rgba(85, 85, 85, 0.3)',
        },
        '&.teammateViewing': {
            border: '#69ff40 1px solid',
            boxShadow: 'inset 0 0 5px 0 #69ff40',
            backgroundColor: 'rgba(105, 255, 64, 0.3)',
        },
        '&.accepted': {
            border: '#ff4081 1px solid',
            boxShadow: 'inset 0 0 5px 0 #ff4081',
            backgroundColor: 'rgba(255, 64, 129, 0.3)',
        },
        '&.ready': {
            border: '#555 1px solid',
            boxShadow: 'inset 0 0 5px 0 #555',
            backgroundColor: 'rgba(85, 85, 85, 0.3)',
        },
    },
    QuestionLink: {
        display: 'flex',
        width: '70%',
        height: '70%',
        padding: '15%',
        alignItems: 'center',
        justifyContent: 'center',
        textDecoration: 'none',
        '&.large': {
            width: '100%',
            height: '100%',
            padding: '0',
        }
    },
    QuestionLinkImg: {
        width: 'auto',
        height: '100%',
    },
    QuestionLinkImgResult: {
        position: 'absolute',
        top: '0',
        left: '0',
        width: 'auto',
        height: '100%',
        pointerEvents: 'none',
    }
});

export default Styles;